name: Release WPF Application

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger quando fai push di tag tipo v1.0.0

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build and Publish (Self-contained)
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x64
      
      - name: Create ZIP archive
        run: |
          Compress-Archive -Path ./publish/win-x64/* -DestinationPath ./SigmaMS-win-x64.zip
        shell: pwsh
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./SigmaMS-win-x64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}